export const dev = {
  baseUrlSwagger: "https://localhost:7193/",
  baseUrlNormal: "http://localhost:5212/",
  baseApiUrlSwagger: "https://localhost:7193/api",
  baseApiUrlNormal: "https://localhost:5212/api",
  motorizationUrl: "https://localhost:7193/api/Motorization",
  brandUrl: "https://localhost:7193/Brand",
  carPoolUrl: "https://localhost:7193/CarPool",
  carPoolPassengerUrl: "https://localhost:7193/CarPoolPassenger",
  categoryUrl: "https://localhost:7193/Category",
  modelUrl: "https://localhost:7193/Model",
  rentUrl: "https://localhost:7193/Rent",
  userUrl: "https://localhost:7193/User",
  vehicleUrl: "https://localhost:7193/Vehicle",
};
